services:
  #register custom service
  App\Bundle\SymfonyTpl\Service\SymfonyTplService:
    autowire: true
    public: true
  #Register and Autowire All Repository
  App\Bundle\SymfonyTpl\Repository\:
    autowire: true
    resource: '../../Repository/*'
    tags: ['doctrine.repository_service']
  #registering a locale listener to use the melis platform language with higher priority
  App\Bundle\SymfonyTpl\EventListener\LocaleListener:
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }